services:
  client:
    build: client/
    depends_on:
      - server
    restart: always

  server:
    build: ./
    depends_on:
      - db
    restart: always
    env_file: local.env

  db:
    image: postgres:16-alpine
    restart: always
    env_file: local.env
