services:
  client:
    build: client/
    depends_on:
      - server
    restart: always
    ports:
      - "8080:80"

  server:
    build: ./
    depends_on:
      - db
    restart: always
    env_file: local.env
    ports:
      - "5248:5248"

  db:
    image: postgres:16-alpine
    restart: always
    env_file: local.env
    ports:
      - "5432:5432"
